routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
})->name('index');


Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/locations', 'Backend\LocationController');

        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');
        Route::resource('/products', 'Backend\ProductController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);


        //User Order History

        Route::get('/order-history', 'Backend\OrderController@index')->name('get.order.history');
        Route::get('/order/{id}', 'Backend\OrderController@showOrder')->name('get.user.order.show');
        Route::delete('/order/delete/{id}', 'Backend\OrderController@destroy')->name('get.user.order.delete');

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


        // Send Notifications

        Route::get('/notification/index', 'Backend\NotificationController@index')->name('notification.index');
        Route::post('/notification/send', 'Backend\NotificationController@send')->name('notification.send');


    });

});



//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('update/order/status', 'Backend\AjaxController@orderStatus')->name('update.order');
});

app/Http/Controllers/Api/OrderController.php
<?php

namespace App\Http\Controllers\Api;


use App\Http\Controllers\Controller;
use App\Http\Resources\Customer\OrderResource;
use App\Models\Notification;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\Product;
use App\Models\User;
use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class OrderController extends Controller
{
    use GeneralHelperTrait;

    public function orders()
    {
        try {

            $user = Auth::user();
            return response()->json(['data' => OrderResource::collection(Order::where('customer_id', $user->id)->orderBy('id', 'desc')->get())], 200);

        } catch (QueryException $exception) {
            return response()->json($exception, 404);
        }
    }

    public function store(Request $request)
    {
        $finalOrder = json_decode($request->finalOrder, true);
        $validator = Validator::make($finalOrder, [
            'first_name' => 'required',
            'last_name' => 'required',
            'email_address' => 'required',
            'phone_number' => 'required',
            'address' => 'required',
            'total' => 'required',
            'shop_name' => 'required',
            'delivery_charges' => 'required',
        ], [
            'shop_name.required' => 'Shop Name is required',
            'delivery_charges.required' => 'Delivery Charges is required',
        ]);

        if ($validator->fails()) {
            return response()->json(['error' => $validator->errors()], 400);
        }

        try {

            if (!empty($finalOrder)) {
                $user = Auth::user();
                $order_id = $this->orderNumber();

                $order = Order::create([

                    'customer_id' => $user->id,
                    'order_id' => $order_id,
                    'first_name' => $finalOrder['first_name'],
                    'last_name' => $finalOrder['last_name'],
                    'area' => $finalOrder['shop_name'],
                    'email_address' => $finalOrder['email_address'],
                    'phone_number' => $finalOrder['phone_number'],
                    'address' => $finalOrder['address'],
                    'shipping_price' => $finalOrder['delivery_charges'],
                    'total' => $finalOrder['total'],
                    'order_status' => 'pending',

//                    'company_name'           => $finalOrder['company_name'],
//                    'country'                => $finalOrder['country'],
//                    'city'                   => $finalOrder['city'],
//                    'state'                  => $finalOrder['state'],
//                    'post_code'              => $finalOrder['post_code'],
//                    'special_instruction'    => $finalOrder['special_instruction'],
//                    'sub_total'              => $finalOrder['sub_total'],
//                    'shipping_price'         => $finalOrder['shipping_price'],
//                    'payment_method'         => $finalOrder['payment_method'],
//                    'time_zone'              => $finalOrder['timeZone'],

                ]);


                if (!empty($finalOrder['products'])) {
                    foreach ($finalOrder['products'] as $products) {

                        $productData = Product::where('id', (int)$products['product_id'])->first();
                        if (!is_null($productData)) {
                            $order_details = OrderDetail::create([
                                'order_id' => $order->id,
                                'products_id' => $products['product_id'],
                                'name' => $productData->name,
                                'quantity' => $products['quantity'],
                                'amount' => $productData->amount,
                            ]);
                        }


                    }

                }



                $message = 'Thank you for your order with Smart Food Products!';
                $message2 = 'Someone from our team will be calling you shortly to confirm your order.Your Order ID is:' . $order_id . '.';
                return response()->json(['status' => true, 'message' => $message, 'message2' => $message2, 'data' => OrderResource::collection(Order::where('id', $order->id)->get())], 200);
            } else {
                return response()->json(['status' => true, 'message' => 'Data  not found'], 401);
            }

        } catch (QueryException $exception) {
            return response()->json($exception, 404);
        }


    }

}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{

    public function orderStatus(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'order_id' => 'required|exists:orders,id',
            'order_status' => 'required'
        ], [
            'order_id.required' => "Order is Required.",
            'order_id.exists' => "Invalid Order Selected."
        ]);

        if (!$validator->fails()) {
            $order = Order::where('id', $request->get('order_id'))->update([
                'order_status' => $request->get('order_status'),
            ]);


            $getOrder = Order::where('id' ,$request->order_id)->first();
            $user = User::where('id', $getOrder->customer_id)->first();
            if (!is_null($user->fcm_token) && $request->get('order_status') == 'confirmed') {
                $notification = new Notification();
                $notification->toSingleDevice($user->fcm_token, 'Smart Food Products', 'Your order has been ' . ucfirst($request->get('order_status')) . '. It will be delivered in 7 working days.', null, null);

            }


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }

}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\City;
use Illuminate\Http\Request;

class CityController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $cities = City::orderBy('id', 'DESC')->get();

        return view('backend.cities.index', compact('cities'));
    }

    public function create()
    {
        return view('backend.cities.create');

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);
        City::create($request->all());
        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City created successfully.'
            ]);

    }

    public function edit($id)
    {
        $city = City::find($id);
        return view('backend.cities.edit', compact('city'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);
        City::find($id)->update($request->all());
        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $city = City::findOrFail($id);
        $city->delete();

        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users_count = User::all()->count();
        $total_orders = Order::all()->count();
        return view('backend.dashboard.index', compact('users_count', 'total_orders'));
    }
}

app/Http/Controllers/Backend/LocationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocationController extends Controller
{

    public function __construct()
    {
        $this->middleware('role:admin');
    }



    public function index()
    {
        $locations = Location::all();

        return view('backend.locations.index', compact('locations'));
    }


    public function create()
    {
        return view('backend.locations.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'address'       => 'required',
            'latitude'      => 'required',
            'longitude'     => 'required',
        ],[
            'address.required'      => 'Shop Address is required.',
            'latitude.required'     => 'Latitude is required.',
            'longitude.required'    => 'Longitude is required.'
        ]);
        Location::create($request->all());
        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location created successfully.'
            ]);
    }


    public function show(Location $location)
    {
        //
    }


    public function edit($id)
    {
        $location = Location::find($id);
        return view('backend.locations.edit', compact('location'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'address'       => 'required',
            'latitude'      => 'required',
            'longitude'     => 'required',
        ],[
            'address.required'      => 'Shop Address is required.',
            'latitude.required'     => 'Latitude is required.',
            'longitude.required'    => 'Longitude is required.'
        ]);
        Location::find($id)->update($request->all());
        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $location = Location::findOrFail($id);
        $location->delete();

        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Events\SendReferralCodeWithPhone;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Deal;
use App\Models\DealService;
use App\Models\DealSubCategory;
use App\Models\DealSubCategoryAddon;
use App\Models\Driver;
use App\Models\FirstOrderDiscount;
use App\Models\MembershipDiscount;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\OrderMenuItemAddon;
use App\Models\ReferralDiscount;
use App\Models\Product;
use App\Models\Staff;
use App\Models\StaffServices;
use App\Models\User;
use App\Models\UserReferral;
use App\Traits\GeneralHelperTrait;
use Carbon\Carbon;
use Facade\Ignition\Support\Packagist\Package;
use Illuminate\Http\Request;
use function GuzzleHttp\Promise\all;

class OrderController extends Controller
{

    use GeneralHelperTrait;

    public function index(Request $request)
    {

        $orders = Order::whereNotNull('id');

        if (!is_null($request->status)) {

            $orders->where('order_status', $request->status);

        }

        if (!is_null($request->start_date)) {

            $orders->whereDate('created_at', '>=', $request->start_date);

        }

        if (!is_null($request->end_date)) {

            $orders->whereDate('created_at', '<=', $request->end_date);
        }

        $orders = $orders->get();
        return view('backend.orders.index', compact('orders'));
    }

    public function showOrder($id)
    {
        $order = Order::findOrFail($id);
        return view('backend.orders.show', compact('order'));

    }


    public function destroy($id)
    {
        $order = Order::findOrFail($id);
        $order->delete();

        return redirect()->route('admin.get.order.history')->with([
            'flash_status' => 'success',
            'flash_message' => 'Order Deleted Successfully.',
        ]);
    }
}

resources/views/backend/orders/index.blade.php
@extends('layouts.master')
@section('title','Orders')
@push('css')
    <style>
        .map-image {
            height: 60px;
            width: 60px;
            border-radius: 50px !important;
            margin-right: 15px;
            float: left;
        }

        .mw-100 {
            margin: 0 auto;
        }

    </style>
@endpush
@section('content')
    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Orders History
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <span>
                                <span><strong>No of orders: {{ $orders->count() }}</strong> </span>
                            </span>
                        </li>
                    </ul>
                </div>

            </div>

            <div class="m-portlet__body">


                <form action="{{ route('admin.get.order.history') }}" method="GET" enctype="multipart/form-data">
                    <div class="form-group row">
                        <div class="col-md-12">
                            <h4>Filter</h4>
                        </div>
                        <div class="col-md-3 col-sm-3 col-xl-3">


                            <label for="start_date" class="col-md-6 col-form-label text-md-left"><strong>Start
                                    Date:</strong></label>

                            <input type="date" class="form-control" id="start_date" name="start_date"
                                   value="{{ old('start_date') }}">


                        </div>
                        <div class="col-md-3 col-sm-3 col-xl-3">
                            <label for="end_date" class="col-md-6 col-form-label text-md-left"><strong>End
                                    Date:</strong></label>
                            <input type="date" class="form-control" id="end_date" name="end_date"
                                   value="{{ old('end_date') }}">
                        </div>
                        <div class="col-md-3 col-sm-3 col-xl-3">

                            <label for="status"
                                   class="col-md-4 col-form-label text-md-left"><strong>Status:</strong></label>

                            <select id="status"
                                    class="form-control @error('status') is-invalid @enderror"
                                    name="status" autocomplete="status">

                                <option value="">Select an option</option>
                                <option value="pending" {{ (request()->get('status') == 'pending') ? 'selected' : '' }}>
                                    Pending
                                </option>
                                <option
                                    value="confirmed" {{ (request()->get('status') == 'confirmed') ? 'selected' : '' }}>
                                    Confirmed
                                </option>
                                <option
                                    value="completed" {{ (request()->get('status') == 'completed') ? 'selected' : '' }}>
                                    Completed
                                </option>
                            </select>

                        </div>
                        <div class="col-md-3 col-sm-3 col-xs-3">
                            <div class="m-form__actions m-form__actions">
                                <label style="display: block"
                                       class="col-md-4 col-form-label text-md-left">&nbsp;</label>
                                <a href="{{ route('admin.get.order.history') }}"
                                   class="btn btn-accent m-btn m-btn--icon m-btn--air refreshBtn">
                                <span>
                                    <i class="la la-refresh"></i>

                                </span>
                                </a>
                                <button class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    Submit
                                </button>
                            </div>
                        </div>
                    </div>


                </form>


                <hr>
                {{--tableScroll--}}

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th> Order No.</th>
                        <th> Customer Name</th>
                        <th> Shop Name</th>
                        <th width="10%"> Total Price</th>
                        <th width="10%"> Address</th>
                        <th>Order Status</th>
                        <th>Booking Date</th>
                        <th width="15%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($orders))
                        @foreach($orders as $key=>$order)
                            @if(!is_null($order->user))
                                <tr>
                                    <td>{{$order->order_id}}</td>
                                    <td>{{ucfirst($order->first_name)}} {{ ucfirst($order->last_name) }}</td>
                                    <td>{{ucfirst($order->area)}}</td>
                                    <td>£{{$order->total ?? 0}}</td>
                                    <td>{{$order->address ?? '--'}}</td>
                                    <td>
                                        <input type="hidden" value="{{$order->id}}" id="order_id">
                                        <select id="order_status" name="order_status"
                                                class="form-control @error('order_status') is-invalid @enderror"
                                                autocomplete="status" autofocus>
                                            <option
                                                value="pending" {{ (old('order_status',$order->order_status) == 'pending') ? 'selected' : ''  }}>
                                                Pending
                                            </option>
                                            <option
                                                value="confirmed" {{ (old('order_status',$order->order_status) == 'confirmed') ? 'selected' : ''  }}>
                                                Confirmed
                                            </option>
                                            <option
                                                value="completed" {{ (old('order_status',$order->order_status) == 'completed') ? 'selected' : ''  }}>
                                                Completed
                                            </option>
                                        </select>

                                    </td>
                                    <td>{{ date('d-m-Y', strtotime($order->created_at)) }}</td>
                                    {{--                                    <td>{{\Carbon\Carbon::parse($order->created_at)->setTimezone($order->time_zone)->format('d/m/Y h:i A')}}</td>--}}
                                    <td nowrap>
                                        <a href="{{route('admin.get.user.order.show',$order->id)}}"
                                           class="btn btn-sm btn-info pull-left ">View</a>
                                    </td>
                                </tr>
                            @endif
                        @endforeach
                    @endif
                    </tbody>
                </table>

            </div>
        </div>
    </div>
@endsection
@push('models')

@endpush
@push('js')

    <script>


        var table = $("#m_table_1").DataTable({
            "order": [[0, "desc"]],
            "columnDefs": [
                {orderable: false, targets: [5]}
            ],
        });

        $(document).on('change', '#order_status', function () {
            var order_id = $('#order_id').val();
            var order_status = $(this).val();

            var request = {"order_id": order_id, "order_status": order_status};
            if (order_status !== '' && order_id !== '') {
                $.ajax({
                    type: "GET",
                    url: "{{ route('ajax.update.order') }}",
                    data: request,
                    dataType: "json",
                    cache: true,
                    success: function (response) {
                        if (response.status == "success") {
                            toastr['success']("Order Status Updated Successfully");
                        }
                    },
                    error: function () {
                        toastr['error']("Something Went Wrong.");
                    }
                });
            } else {
                toastr['error']("Please Select Order Status");
            }


        });


    </script>



@endpush