routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('auth.login');
})->name('index');


Route::get('/cache', function () {

    \Illuminate\Support\Facades\Artisan::call('key:generate');
//    \Illuminate\Support\Facades\Artisan::call('storage:link');
    \Illuminate\Support\Facades\Artisan::call('cache:clear');
    \Illuminate\Support\Facades\Artisan::call('config:clear');
    \Illuminate\Support\Facades\Artisan::call('view:clear');
    \Illuminate\Support\Facades\Artisan::call('route:clear');
    \Illuminate\Support\Facades\Artisan::call('config:cache');

//    \Illuminate\Support\Facades\Artisan::call('passport:install');
    \Illuminate\Support\Facades\Artisan::call('migrate');

    return 'Commands run successfully Cleared.';
});


// Authentication Routes...
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
Route::get('/register/{referral_code?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
Route::post('register', 'Auth\RegisterController@register');

// Password Reset Routes...
Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
Route::post('password/reset', 'Auth\ResetPasswordController@reset')->name('password.update');

Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth'])->group(function () {
    Route::prefix('admin')->name('admin.')->group(function () {
        Route::resource('/dashboard', 'Backend\DashboardController');
        Route::resource('/cities', 'Backend\CityController');
        Route::resource('/locations', 'Backend\LocationController');

        Route::resource('/users', 'Backend\UserController');
        Route::post('/users/location', 'Backend\UserController@updateLocation')->name('user.location');
        Route::resource('/products', 'Backend\ProductController');
        Route::resource('/settings', 'Backend\SettingController', [
            'only' => ['index', 'edit', 'update']
        ]);
        Route::resource('/privacypolicy', 'Backend\PrivacyController', [
            'only' => ['index', 'store']
        ]);


        //User Order History

        Route::get('/order-history', 'Backend\OrderController@index')->name('get.order.history');
        Route::get('/order/{id}', 'Backend\OrderController@showOrder')->name('get.user.order.show');
        Route::delete('/order/delete/{id}', 'Backend\OrderController@destroy')->name('get.user.order.delete');

        //User Profiles
        Route::get('profile', 'Backend\ProfileController@index')->name('profile.index');

        Route::get('edit/profile', 'Backend\ProfileController@editProfile')->name('profile.edit');
        Route::post('edit/profile/image', 'Backend\ProfileController@editProfileImage')->name('profile.edit.image');
        Route::post('update/profile', 'Backend\ProfileController@updateProfile')->name('update.user.profile');

        Route::get('update/password/', 'Backend\ProfileController@changePassword')->name('update.password');
        Route::post('update/user/password/', 'Backend\ProfileController@updatePassword')->name('update.user.password');

        Route::get('update/phone', 'Backend\ProfileController@changeMobileNumber')->name('update.phone');
        Route::post('update/phone', 'Backend\ProfileController@updateMobileNumber')->name('update.user.phone');


        // Send Notifications

        Route::get('/notification/index', 'Backend\NotificationController@index')->name('notification.index');
        Route::post('/notification/send', 'Backend\NotificationController@send')->name('notification.send');


    });

});



//Ajax Routes
Route::prefix('ajax')->name('ajax.')->group(function () {
    Route::get('update/order/status', 'Backend\AjaxController@orderStatus')->name('update.order');
});

app/Models/City.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $table = 'cities';
    protected $guarded = [];

}

app/Http/Controllers/Backend/AjaxController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Notification;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class AjaxController extends Controller
{

    public function orderStatus(Request $request)
    {
        $response = array('status' => '', 'message' => "", 'data' => array());

        $validator = Validator::make($request->all(), [
            'order_id' => 'required|exists:orders,id',
            'order_status' => 'required'
        ], [
            'order_id.required' => "Order is Required.",
            'order_id.exists' => "Invalid Order Selected."
        ]);

        if (!$validator->fails()) {
            $order = Order::where('id', $request->get('order_id'))->update([
                'order_status' => $request->get('order_status'),
            ]);


            $getOrder = Order::where('id' ,$request->order_id)->first();
            $user = User::where('id', $getOrder->customer_id)->first();
            if (!is_null($user->fcm_token) && $request->get('order_status') == 'confirmed') {
                $notification = new Notification();
                $notification->toSingleDevice($user->fcm_token, 'Smart Food Products', 'Your order has been ' . ucfirst($request->get('order_status')) . '. It will be delivered in 7 working days.', null, null);

            }


            $response['status'] = 'success';
        } else {
            $response['status'] = 'error';
            $response['message'] = "Validation Errors.";
            $response['data'] = $validator->errors()->toArray();
        }

        return $response;

    }

}

app/Http/Controllers/Backend/CityController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\City;
use Illuminate\Http\Request;

class CityController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $cities = City::orderBy('id', 'DESC')->get();

        return view('backend.cities.index', compact('cities'));
    }

    public function create()
    {
        return view('backend.cities.create');

    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);
        City::create($request->all());
        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City created successfully.'
            ]);

    }

    public function edit($id)
    {
        $city = City::find($id);
        return view('backend.cities.edit', compact('city'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'slug' => 'required',
        ]);
        City::find($id)->update($request->all());
        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City updated successfully.'
            ]);

    }

    public function destroy($id)
    {
        $city = City::findOrFail($id);
        $city->delete();

        return redirect()->route('admin.cities.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'City has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\User;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware('role:admin');
    }

    public function index()
    {
        $users_count = User::all()->count();
        $total_orders = Order::all()->count();
        return view('backend.dashboard.index', compact('users_count', 'total_orders'));
    }
}

app/Http/Controllers/Backend/LocationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Location;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class LocationController extends Controller
{

    public function __construct()
    {
        $this->middleware('role:admin');
    }



    public function index()
    {
        $locations = Location::all();

        return view('backend.locations.index', compact('locations'));
    }


    public function create()
    {
        return view('backend.locations.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            'address'       => 'required',
            'latitude'      => 'required',
            'longitude'     => 'required',
        ],[
            'address.required'      => 'Shop Address is required.',
            'latitude.required'     => 'Latitude is required.',
            'longitude.required'    => 'Longitude is required.'
        ]);
        Location::create($request->all());
        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location created successfully.'
            ]);
    }


    public function show(Location $location)
    {
        //
    }


    public function edit($id)
    {
        $location = Location::find($id);
        return view('backend.locations.edit', compact('location'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'address'       => 'required',
            'latitude'      => 'required',
            'longitude'     => 'required',
        ],[
            'address.required'      => 'Shop Address is required.',
            'latitude.required'     => 'Latitude is required.',
            'longitude.required'    => 'Longitude is required.'
        ]);
        Location::find($id)->update($request->all());
        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location updated successfully.'
            ]);
    }

    public function destroy($id)
    {
        $location = Location::findOrFail($id);
        $location->delete();

        return redirect()->route('admin.locations.index')
            ->with([
                'flash_status' => 'success',
                'flash_message' => 'Location has been deleted'
            ]);
    }
}

app/Http/Controllers/Backend/NotificationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Helpers\SendSms;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\User;
use App\Traits\GeneralHelperTrait;
use Illuminate\Http\Request;
use App\Models\Notification;

class NotificationController extends Controller
{
    use GeneralHelperTrait;
    public function index(Request $request)
    {
        return view('backend.notification.index');
    }

    public function send(Request $request)
    {

        $notification_id = 'e8KJFDmhRH-6am8Yseum1_:APA91bEKlp-qyFJ4sfBngrZLCngETUgYIF5uyjVryMeTOK_8okB9PvoNK8WEYr-ym468nzGaraaZQfef0mDZ5nUdxoPFefwGnaVMl0tvaVKM8gmX-xlVBsrS3s0UNHvcQM6NzH_oA4TL';
        $title = "Greeting Notification";
        $message = "Have good day!";
        $id = 1;
        $type = "basic";

        $res = $this->send_notification_FCM($notification_id, $title, $message, $id,$type);

        if($res == 1){


            dd(true);
            // success code

        }else{
            dd('false');
            // fail code
        }



//        $users = User::whereNotNull('fcm_token')->get();
////        $notification = new Notification();
//
//
//        $to ="e8KJFDmhRH-6am8Yseum1_:APA91bEKlp-qyFJ4sfBngrZLCngETUgYIF5uyjVryMeTOK_8okB9PvoNK8WEYr-ym468nzGaraaZQfef0mDZ5nUdxoPFefwGnaVMl0tvaVKM8gmX-xlVBsrS3s0UNHvcQM6NzH_oA4TL";
//        $data = array(
//            'body' => 'new message'
//        );
//
//
//        $arrNotification= array();
//        $arrData = array();
//        $arrNotification["body"] ="Test by Vijay.";
//        $arrNotification["title"] = "PHP ADVICES";
//        $arrNotification["sound"] = "default";
//        $arrNotification["type"] = 1;
//
//        $result = $this->send_notification($to, $arrNotification,"Android");
//
//
////
////        $data = $this->sendPushNotification($to,$data);
//        dd($result);
////        $notification->toSingleDevice($to, 'Smart Food Products', '' . 'hhh' . ' ' . 'azeem' . '', null, null);
//
////        foreach ($users as $user) {
////
////
////            $products = Product::where('quantity', '=', 0)->get();
////
//////            if (!empty($products) && count($products) > 0) {
//////                foreach ($products as $product) {
//////                    $notification->toSingleDevice($user->fcm_token, 'Smart Food Products', '' . $request->message . ' ' . $product->name . '', null, null);
//////                }
//////                $message = 'Notification send successfully.';
//////            } else {
//////                $message = 'No Products out of stock.';
//////            }
////        }
//
////        return redirect()->route('admin.notification.index')
////            ->with([
////                'flash_status' => 'success',
////                'flash_message' => 'lllll'
////            ]);
    }
}

app/Http/Controllers/Backend/OrderController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Events\SendReferralCodeWithPhone;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Deal;
use App\Models\DealService;
use App\Models\DealSubCategory;
use App\Models\DealSubCategoryAddon;
use App\Models\Driver;
use App\Models\FirstOrderDiscount;
use App\Models\MembershipDiscount;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\OrderMenuItemAddon;
use App\Models\ReferralDiscount;
use App\Models\Product;
use App\Models\Staff;
use App\Models\StaffServices;
use App\Models\User;
use App\Models\UserReferral;
use App\Traits\GeneralHelperTrait;
use Carbon\Carbon;
use Facade\Ignition\Support\Packagist\Package;
use Illuminate\Http\Request;
use function GuzzleHttp\Promise\all;

class OrderController extends Controller
{

    use GeneralHelperTrait;

    public function index(Request $request)
    {

        $orders = Order::whereNotNull('id');

        if (!is_null($request->status)) {

            $orders->where('order_status', $request->status);

        }

        if (!is_null($request->start_date)) {

            $orders->whereDate('created_at', '>=', $request->start_date);

        }

        if (!is_null($request->end_date)) {

            $orders->whereDate('created_at', '<=', $request->end_date);
        }

        $orders = $orders->get();
        return view('backend.orders.index', compact('orders'));
    }

    public function showOrder($id)
    {
        $order = Order::findOrFail($id);
        return view('backend.orders.show', compact('order'));

    }


    public function destroy($id)
    {
        $order = Order::findOrFail($id);
        $order->delete();

        return redirect()->route('admin.get.order.history')->with([
            'flash_status' => 'success',
            'flash_message' => 'Order Deleted Successfully.',
        ]);
    }
}

app/Http/Controllers/Backend/PrivacyController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\PrivacyPolicy;
use Illuminate\Http\Request;

class PrivacyController extends Controller
{
    public function index()
    {
        $privacyPolicy = PrivacyPolicy::first();
        return view('backend.privacypolicy.create', compact('privacyPolicy'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'description' => 'required',
        ], [
            'description.required' => 'Description is required.'
        ]);
        $privacyPolicy = PrivacyPolicy::findOrFail(1);

        $privacyPolicy->update([
            'description' => $request->description
        ]);
        return back()->with([
            'flash_status' => 'success',
            'flash_message' => 'Privacy Policy description updated successfully.'
        ]);
    }
}

resources/views/backend/cities/create.blade.php
@extends('layouts.master')
@section('title','Cities')
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
{{--            <div class="m-portlet__head">--}}
{{--                <div class="m-portlet__head-caption">--}}
{{--                    <div class="m-portlet__head-title">--}}
{{--                        <h3 class="m-portlet__head-text">--}}
{{--                            Add {{ __('City') }}--}}
{{--                        </h3>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.cities.store') }}"
                              enctype="multipart/form-data" role="form">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">

                                    <div class="form-group row">


                                        <div class="col-md-6">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('City Name') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{{ old('name') }}"
                                                   autocomplete="name" autofocus>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="slug"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Slug') }} <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="slug" type="text"
                                                   class="form-control @error('slug') is-invalid @enderror"
                                                   name="slug" value="{{ old('slug') }}"
                                                   autocomplete="slug" autofocus>

                                            @error('slug')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.cities.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection

@push('js')
    <script>
        $('#name').focusout(function () {

            var name = $(this).val();
            name = name.replace(/\s+/g, '-').toLowerCase();

            $('#slug').val(name);
        })
    </script>
@endpush

resources/views/backend/cities/edit.blade.php
@extends('layouts.master')
@section('title','Cities')
@section('content')


    <div class="m-content">
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Edit {{ __('City') }}
                        </h3>
                    </div>
                </div>
            </div>

            <div class="m-portlet__body">
                <div class="col-lg-12">
                    <div class="m-portlet">
                        <form class="m-form" method="post" action="{{ route('admin.cities.update', $city->id) }}"
                              enctype="multipart/form-data" role="form">
                            @method('patch')
                            @csrf
                            <div class="m-portlet__body">
                                <div class="m-form__section m-form__section--first">


                                    <div class="form-group row">


                                        <div class="col-md-6">
                                            <label for="name"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('City Name') }}
                                                <span class="mandatorySign">*</span></label>
                                            <input id="name" type="text"
                                                   class="form-control @error('name') is-invalid @enderror"
                                                   name="name" value="{!! $city->name !!}"
                                                   autocomplete="name" autofocus>

                                            @error('name')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>

                                        <div class="col-md-6">
                                            <label for="slug"
                                                   class="col-md-4 col-form-label text-md-left">{{ __('Slug') }} <span
                                                    class="mandatorySign">*</span></label>
                                            <input id="slug" type="text"
                                                   class="form-control @error('slug') is-invalid @enderror"
                                                   name="slug" value="{!! $city->slug !!}"
                                                   autocomplete="slug" autofocus>

                                            @error('slug')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                            @enderror
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit text-md-right">
                                <div class="m-form__actions m-form__actions">
                                    <a href="{{ route('admin.cities.index') }}" class="btn btn-info">Back</a>
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('SAVE') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                        <!--end::Form-->
                    </div>
                    <!--end::Portlet-->
                </div>
            </div>
        </div>
    </div>
@endsection


@push('js')
    <script>
        $('#name').focusout(function () {

            var name = $(this).val();
            name = name.replace(/\s+/g, '-').toLowerCase();

            $('#slug').val(name);
        })
    </script>
@endpush

resources/views/backend/cities/index.blade.php
@extends('layouts.master')
@section('title','Cities')
@section('content')

    <div class="m-content">
        <!--Begin::Section-->
        <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <h3 class="m-portlet__head-text">
                            Cities
                        </h3>
                    </div>
                </div>

                <div class="m-portlet__head-tools">
                    <ul class="m-portlet__nav">
                        <li class="m-portlet__nav-item">
                            <a href="{{ route('admin.cities.create') }}"
                               class="btn btn-accent m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                <span>
                                    <i class="la la-plus"></i>
                                    <span>Add City</span>
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="m-portlet__body">

                <table class="table table-striped- table-bordered table-hover table-checkable" id="m_table_1">
                    <thead>
                    <tr>

                        <th> Sr NO.</th>
                        <th> Name</th>
                        <th> Actions</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if(!empty($cities))
                        @foreach($cities as $city)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$city->name}}</td>
                                <td nowrap>
                                    <a href="{{route('admin.cities.edit',$city->id)}}" class="btn btn-sm btn-info pull-left ">Edit</a>
                                    <form method="post" action="{{ route('admin.cities.destroy', $city->id) }}" id="delete_{{ $city->id }}">
                                        @csrf
                                        @method('DELETE')
                                        <a style="margin-left:10px;" class="btn btn-sm btn-danger m-left"
                                           href="javascript:void(0)"
                                           onclick="if(confirmDelete()){ document.getElementById('delete_<?=$city->id?>').submit(); }">
                                            Delete
                                        </a>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection
@push('js')
    <script>
        $("#m_table_1").dataTable({
            "columnDefs": [
                { orderable: false, targets: [2] }
            ],
        });
    </script>
@endpush